typography_spectrum: 0.9499
color:
  brandColors:
    - '#ffffff'
    - '#392620'
    - '#9b6e3b'
    - '#ada7a9'
    - '#fbab57'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.77241
analytics:
  google: UA-83194967-1
  facebook: null
  twitter: null
author:
  name: Gaylyn Capitano
  email: glcapitano@earthlink.net
name: 'Capitano Music Studio '
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: 'Capitano Music Studio '
purpose: []
