name: 'Capitano Music Studio '
favicon: null
layout_spectrum: 0.82296
typography_spectrum: 0.76025
title: "Ocala's Piano Studio "
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#11242b'
    - '#b0a0a0'
    - '#dbd2ca'
    - '#7b6960'
    - '#9c473f'
  brandStrength: 0
  lightness: 1
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
