name: 'Capitano Music Studio '
favicon: null
layout_spectrum: 0.57515
typography_spectrum: 0.9499
title: 'Capitano Music Studio '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#392620'
    - '#9b6e3b'
    - '#ada7a9'
    - '#fbab57'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
