name: 'Capitano Music Studio '
favicon: null
layout_spectrum: 0.59936
typography_spectrum: 0.9499
title: 'Capitano Music Studio '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000a00'
    - '#c30821'
    - '#99a4a8'
    - '#766344'
    - '#106f98'
  brandStrength: 0
  lightness: 0.8125
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
